#server:
#  port: 10

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
cloud:
  aws:
    credentials:
      access-key: AKIAUTOA72WJ332ADLH2
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: lamdt-aws-demo

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui.path: /swagger-ui.html

management.security.enabled: false
jwtSecret : lamdt.com.vn
jwtExpirationMs: 86400000