#cloud:
#  aws:
#    credentials:
#      access-key: AKIASUHNUQ3SWVOV466O
#      secret-key: 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
#    region:
#      static: ap-southeast-1
#    stack:
#      auto: false

#application:
# bucket:
#    name: home-sharing